// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyrJrj3x-8Qd9ZRft5ioI5Ui0ko0bAIEc',
    appId: '1:260293907781:web:325f209254ba56dba8da2c',
    messagingSenderId: '260293907781',
    projectId: 'mailfl',
    authDomain: 'mailfl.firebaseapp.com',
    storageBucket: 'mailfl.appspot.com',
    measurementId: 'G-7J94P5Y1L0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXr_TQmtCCh0bo3xdEfcHEqUTXoq9ywAM',
    appId: '1:260293907781:android:3d7717f2569811ffa8da2c',
    messagingSenderId: '260293907781',
    projectId: 'mailfl',
    storageBucket: 'mailfl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6sYLIdJBQ_IQIEjPs5R2vatCNVzAnK-0',
    appId: '1:260293907781:ios:162efc3ea14f5d67a8da2c',
    messagingSenderId: '260293907781',
    projectId: 'mailfl',
    storageBucket: 'mailfl.appspot.com',
    iosBundleId: 'com.example.flutteremailpasse',
  );
}
